#!/usr/bin/env bash
set -euo pipefail

# One-shot installer for the LFHCal yall-integration environment.
#
# Default layout:
#   ~/eic-2026/eic-shell
#   ~/eic-2026/yall-run
#   ~/eic-2026/epic-lfhcal-tbana
#   ~/eic-2026/.venv-yall
#   ~/eic-2026/data/TB2026
#   ~/eic-2026/work
#
# Override the install root before invoking the script:
#   LFHCAL_HOME=/path/to/eic-2026 bash bootstrap-yall-integration.sh

LFHCAL_HOME=${LFHCAL_HOME:-"$HOME/eic-2026"}
YALL_REPO_URL=${YALL_REPO_URL:-"https://github.com/paulnord/yall-run.git"}
LFHCAL_REPO_URL=${LFHCAL_REPO_URL:-"https://github.com/paulnord/epic-lfhcal-tbana.git"}
YALL_BRANCH=${YALL_BRANCH:-main}
LFHCAL_BRANCH=${LFHCAL_BRANCH:-yall-integration}
LFHCAL_BUILD_JOBS=${LFHCAL_BUILD_JOBS:-2}

YALL_DIR="$LFHCAL_HOME/yall-run"
LFHCAL_DIR="$LFHCAL_HOME/epic-lfhcal-tbana"
VENV_DIR="$LFHCAL_HOME/.venv-yall"
EIC_SHELL="$LFHCAL_HOME/eic-shell"

say() {
    printf '\n==> %s\n' "$*"
}

need() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "Required command not found: $1" >&2
        exit 1
    }
}

update_checkout() {
    local url=$1
    local branch=$2
    local dir=$3

    if [[ -d "$dir/.git" ]]; then
        say "Updating $(basename "$dir") ($branch)"
        git -C "$dir" fetch origin
        git -C "$dir" switch "$branch"
        git -C "$dir" pull --ff-only
    else
        say "Cloning $(basename "$dir") ($branch)"
        git clone --branch "$branch" "$url" "$dir"
    fi
}

need git
need curl
need python3
need cmake

mkdir -p "$LFHCAL_HOME"

if [[ ! -x "$EIC_SHELL" ]]; then
    say "Installing eic-shell"
    (
        cd "$LFHCAL_HOME"
        curl --fail --silent --show-error --location https://get.epic-eic.org | bash
    )

    # Some installations place the launcher under eic-env. Keep one stable
    # path for the LFHCal examples and batch workers.
    if [[ ! -x "$EIC_SHELL" && -x "$LFHCAL_HOME/eic-env/eic-shell" ]]; then
        ln -s "$LFHCAL_HOME/eic-env/eic-shell" "$EIC_SHELL"
    fi
fi

if [[ ! -x "$EIC_SHELL" ]]; then
    echo "eic-shell was not found at $EIC_SHELL after installation." >&2
    exit 1
fi

update_checkout "$YALL_REPO_URL" "$YALL_BRANCH" "$YALL_DIR"
update_checkout "$LFHCAL_REPO_URL" "$LFHCAL_BRANCH" "$LFHCAL_DIR"

say "Installing yall-run in a host-side virtual environment"
if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    python3 -m venv "$VENV_DIR"
fi
"$VENV_DIR/bin/python" -m pip install --upgrade pip
"$VENV_DIR/bin/python" -m pip install -e "$YALL_DIR"

say "Configuring LFHCal inside eic-shell"
"$LFHCAL_DIR/tools/run-in-eic-shell.sh" "$EIC_SHELL" \
    cmake -S "$LFHCAL_DIR/NewStructure" -B "$LFHCAL_DIR/NewStructure/build"

say "Building LFHCal"
"$LFHCAL_DIR/tools/run-in-eic-shell.sh" "$EIC_SHELL" \
    cmake --build "$LFHCAL_DIR/NewStructure/build" -j"$LFHCAL_BUILD_JOBS"

# Site storage is deliberately kept outside git. The first installation gets
# safe home-directory defaults. Edit these two files once at a site such as
# BNL or CERN to point at shared/scratch storage. Re-running this installer
# preserves local edits.
if [[ ! -f "$LFHCAL_HOME/site-env.sh" ]]; then
    cat > "$LFHCAL_HOME/site-env.sh" <<EOF
# Site-specific LFHCal storage. Edit these paths for this host/site.
export LFHCAL_DATA="${LFHCAL_HOME}/data/TB2026"
export LFHCAL_WORK="${LFHCAL_HOME}/work"
EOF
fi

if [[ ! -f "$LFHCAL_HOME/site-env.tcsh" ]]; then
    cat > "$LFHCAL_HOME/site-env.tcsh" <<EOF
# Site-specific LFHCal storage. Edit these paths for this host/site.
setenv LFHCAL_DATA "${LFHCAL_HOME}/data/TB2026"
setenv LFHCAL_WORK "${LFHCAL_HOME}/work"
EOF
fi

cat > "$LFHCAL_HOME/activate.sh" <<EOF
# Generated by bootstrap-yall-integration.sh
export LFHCAL_HOME="${LFHCAL_HOME}"
export LFHCAL_REPO="${LFHCAL_DIR}"
export YALL_RUN_REPO="${YALL_DIR}"
export EIC_SHELL="${EIC_SHELL}"
export PATH="${VENV_DIR}/bin:\$PATH"
source "${LFHCAL_HOME}/site-env.sh"
mkdir -p "\$LFHCAL_DATA" "\$LFHCAL_WORK" "\$LFHCAL_WORK/campaigns"
EOF

cat > "$LFHCAL_HOME/activate.tcsh" <<EOF
# Generated by bootstrap-yall-integration.sh
setenv LFHCAL_HOME "${LFHCAL_HOME}"
setenv LFHCAL_REPO "${LFHCAL_DIR}"
setenv YALL_RUN_REPO "${YALL_DIR}"
setenv EIC_SHELL "${EIC_SHELL}"
setenv PATH "${VENV_DIR}/bin:\$PATH"
source "${LFHCAL_HOME}/site-env.tcsh"
mkdir -p "\$LFHCAL_DATA" "\$LFHCAL_WORK" "\$LFHCAL_WORK/campaigns"
EOF

mkdir -p "$LFHCAL_HOME/data/TB2026" "$LFHCAL_HOME/work/campaigns"

say "Smoke tests"
"$LFHCAL_DIR/tools/run-in-eic-shell.sh" "$EIC_SHELL" root-config --version
"$VENV_DIR/bin/yall-run" --help >/dev/null

test -x "$LFHCAL_DIR/NewStructure/build/Convert"
test -x "$LFHCAL_DIR/NewStructure/build/DataPrep"

if [[ -f "$LFHCAL_DIR/examples/yall/check_shared_conversions.py" ]]; then
    "$VENV_DIR/bin/python" "$LFHCAL_DIR/examples/yall/check_shared_conversions.py" -v
fi

say "Ready"
printf 'Install root: %s\n' "$LFHCAL_HOME"
printf 'LFHCal:       %s (%s)\n' "$LFHCAL_DIR" "$LFHCAL_BRANCH"
printf 'yall-run:     %s (%s)\n' "$YALL_DIR" "$YALL_BRANCH"
printf 'eic-shell:    %s\n' "$EIC_SHELL"
printf '\nFor tcsh:\n  source %s/activate.tcsh\n' "$LFHCAL_HOME"
printf 'Then enter an example and source its env.tcsh before running yall-run.\n'
