#!/usr/bin/env bash
set -euo pipefail

# BNL setup using the login environment's Python and Condor.
# Run outside eic-shell; only the LFHCal build and payloads use the container.
# Run from a user-created workspace, for example:
#   mkdir my_eic_work_with_LFHCAL && cd my_eic_work_with_LFHCAL
#   curl -fsSL <bootstrap-url> | bash
#
# Sources, eic-shell, activation files, data/TB2026 and work go here.
# yall-run is installed with pip --user -e using the provided host Python.
# An existing LFHCAL_HOME from an activated environment does not redirect
# installation. To select another destination, use bash -s -- --prefix PATH.

install_root=$PWD
while (($#)); do
    case "$1" in
        --prefix)
            if [[ $# -lt 2 || -z "$2" ]]; then
                echo "--prefix requires an installation directory." >&2
                exit 2
            fi
            install_root=$2
            shift 2
            ;;
        -h|--help)
            echo "Usage: bash bootstrap-yall-integration.sh [--prefix PATH]"
            echo "Default destination: the current working directory."
            exit 0
            ;;
        *)
            echo "Unknown argument: $1 (use --help)." >&2
            exit 2
            ;;
    esac
done

YALL_REPO_URL=${YALL_REPO_URL:-"https://github.com/paulnord/yall-run.git"}
LFHCAL_REPO_URL=${LFHCAL_REPO_URL:-"https://github.com/paulnord/epic-lfhcal-tbana.git"}
YALL_BRANCH=${YALL_BRANCH:-main}
LFHCAL_BRANCH=${LFHCAL_BRANCH:-yall-integration}
LFHCAL_BUILD_JOBS=${LFHCAL_BUILD_JOBS:-2}

say() {
    printf '\n==> %s\n' "$*"
}

need() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "Required command not found: $1" >&2
        exit 1
    }
}

update_checkout() {
    local url=$1
    local branch=$2
    local dir=$3

    if [[ -d "$dir/.git" ]]; then
        say "Updating $(basename "$dir") ($branch)"
        git -C "$dir" fetch origin
        git -C "$dir" switch "$branch"
        git -C "$dir" pull --ff-only
    else
        say "Cloning $(basename "$dir") ($branch)"
        git clone --branch "$branch" "$url" "$dir"
    fi
}

need git
need curl
need python3

mkdir -p -- "$install_root"
# Resolve once, before deriving paths or entering installer/build directories.
# In particular, --prefix ./workspace must not become relative to eic-shell.
LFHCAL_HOME=$(cd -- "$install_root" && pwd -P)
YALL_DIR="$LFHCAL_HOME/yall-run"
LFHCAL_DIR="$LFHCAL_HOME/epic-lfhcal-tbana"
EIC_SHELL="$LFHCAL_HOME/eic-shell"

say "Installation root: $LFHCAL_HOME"

if [[ ! -x "$EIC_SHELL" ]]; then
    say "Installing eic-shell"
    (
        cd "$LFHCAL_HOME"
        curl --fail --silent --show-error --location https://get.epic-eic.org | bash
    )

    # Some installations place the launcher under eic-env. Keep one stable
    # path for the LFHCal examples and batch workers.
    if [[ ! -x "$EIC_SHELL" && -x "$LFHCAL_HOME/eic-env/eic-shell" ]]; then
        ln -s "$LFHCAL_HOME/eic-env/eic-shell" "$EIC_SHELL"
    fi
fi

if [[ ! -x "$EIC_SHELL" ]]; then
    echo "eic-shell was not found at $EIC_SHELL after installation." >&2
    exit 1
fi

update_checkout "$YALL_REPO_URL" "$YALL_BRANCH" "$YALL_DIR"
update_checkout "$LFHCAL_REPO_URL" "$LFHCAL_BRANCH" "$LFHCAL_DIR"
git -C "$LFHCAL_DIR" submodule update --init --recursive

say "Installing yall-run for this user with the host Python"
python3 -m pip install --user -e "$YALL_DIR"
YALL_USER_BIN="$(python3 -m site --user-base)/bin"

say "Configuring LFHCal inside eic-shell"
"$LFHCAL_DIR/tools/run-in-eic-shell.sh" "$EIC_SHELL" \
    cmake -S "$LFHCAL_DIR/NewStructure" -B "$LFHCAL_DIR/NewStructure/build"

say "Building LFHCal"
"$LFHCAL_DIR/tools/run-in-eic-shell.sh" "$EIC_SHELL" \
    cmake --build "$LFHCAL_DIR/NewStructure/build" -j"$LFHCAL_BUILD_JOBS"

# Site storage is deliberately kept outside git. The first installation gets
# workspace-local defaults. Edit these two files once at a site such as
# BNL or CERN to point at shared/scratch storage. Re-running this installer
# preserves local edits. Explicit shell variables override the defaults.
if [[ ! -f "$LFHCAL_HOME/site-env.sh" ]]; then
    cat > "$LFHCAL_HOME/site-env.sh" <<EOF
# Site-specific LFHCal storage. Edit these paths for this host/site.
export LFHCAL_DATA="\${LFHCAL_DATA:-${LFHCAL_HOME}/data/TB2026}"
export LFHCAL_WORK="\${LFHCAL_WORK:-${LFHCAL_HOME}/work}"
EOF
fi

if [[ ! -f "$LFHCAL_HOME/site-env.tcsh" ]]; then
    cat > "$LFHCAL_HOME/site-env.tcsh" <<EOF
# Site-specific LFHCal storage. Edit these paths for this host/site.
if (! \$?LFHCAL_DATA) setenv LFHCAL_DATA "${LFHCAL_HOME}/data/TB2026"
if (! \$?LFHCAL_WORK) setenv LFHCAL_WORK "${LFHCAL_HOME}/work"
EOF
fi

cat > "$LFHCAL_HOME/activate.sh" <<EOF
# Generated by bootstrap-yall-integration.sh
export LFHCAL_HOME="${LFHCAL_HOME}"
export LFHCAL_REPO="${LFHCAL_DIR}"
export YALL_RUN_REPO="${YALL_DIR}"
export EIC_SHELL="${EIC_SHELL}"
export PATH="${YALL_USER_BIN}:\$PATH"
source "${LFHCAL_HOME}/site-env.sh"
mkdir -p "\$LFHCAL_DATA" "\$LFHCAL_WORK" "\$LFHCAL_WORK/campaigns"
EOF

cat > "$LFHCAL_HOME/activate.tcsh" <<EOF
# Generated by bootstrap-yall-integration.sh
setenv LFHCAL_HOME "${LFHCAL_HOME}"
setenv LFHCAL_REPO "${LFHCAL_DIR}"
setenv YALL_RUN_REPO "${YALL_DIR}"
setenv EIC_SHELL "${EIC_SHELL}"
setenv PATH "${YALL_USER_BIN}:\$PATH"
rehash
source "${LFHCAL_HOME}/site-env.tcsh"
mkdir -p "\$LFHCAL_DATA" "\$LFHCAL_WORK" "\$LFHCAL_WORK/campaigns"
EOF

mkdir -p "$LFHCAL_HOME/data/TB2026" "$LFHCAL_HOME/work/campaigns"

say "Smoke tests"
"$LFHCAL_DIR/tools/run-in-eic-shell.sh" "$EIC_SHELL" root-config --version
"$YALL_USER_BIN/yall-run" --help >/dev/null

test -x "$LFHCAL_DIR/NewStructure/build/Convert"
test -x "$LFHCAL_DIR/NewStructure/build/DataPrep"

if [[ -f "$LFHCAL_DIR/examples/yall/check_shared_conversions.py" ]]; then
    python3 "$LFHCAL_DIR/examples/yall/check_shared_conversions.py" -v
fi

say "Ready"
printf 'Install root: %s\n' "$LFHCAL_HOME"
printf 'LFHCal:       %s (%s)\n' "$LFHCAL_DIR" "$LFHCAL_BRANCH"
printf 'yall-run:     %s (%s)\n' "$YALL_DIR" "$YALL_BRANCH"
printf 'Command:      %s/yall-run\n' "$YALL_USER_BIN"
printf 'eic-shell:    %s\n' "$EIC_SHELL"
printf '\nFor bash:\n  source "%s/activate.sh"\n' "$LFHCAL_HOME"
printf '\nFor tcsh:\n  source "%s/activate.tcsh"\n' "$LFHCAL_HOME"
printf 'Then enter an example and source its env.sh or env.tcsh before running yall-run.\n'
