#!/usr/bin/env python3
"""Compatibility name for make-tb2026-paramscan-campaign."""

from __future__ import annotations

import os
import pathlib
import sys


target = pathlib.Path(__file__).with_name("make-tb2026-paramscan-campaign")
os.execv(sys.executable, [sys.executable, str(target), *sys.argv[1:]])
