universe = vanilla

executable = /star/u/pnord/eic-2026/epic-lfhcal-tbana/workflow/condor/run_in_eic_container.sh
arguments = /star/u/pnord/eic-2026/epic-lfhcal-tbana/workflow/condor/run_analysis_phase.sh $(phase) $(pedestal) $(muon) $(cpus)

initialdir = /star/u/pnord/eic-2026/epic-lfhcal-tbana
should_transfer_files = NO
getenv = False

request_cpus   = $(cpus)
request_memory = $(memory)
request_disk   = 4GB

notification = Never

output = /star/u/pnord/eic-2026/logs_condor/scan/$(node).$(Cluster).out
error  = /star/u/pnord/eic-2026/logs_condor/scan/$(node).$(Cluster).err
log    = /tmp/pnord/lfhcal-condor/$(node).$(Cluster).log

queue
